######################## default configuration ####################
# Title of your website (required).
title: "The Greeting"
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL: "/"


############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /article/**
      kind: page
    pager: true
    editable: false
    hide_date: false
    show_date_updated: true
    reading_time: false
    commentable: true
    show_related: true
    share: false
    # Just use Breadcrumb for navigation on blog post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Blog section options
  - _target:
      path: /blog/*
      kind: section
    # Set the listing view
    view: date-title-summary

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  meetup: '/meetup/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
timeout: 600000
# taxonomies:
#   tag: tags
#   category: categories
#   author: authors
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep