main:
  - name: Home
    url: /meetup/
    weight: 10
  - name: Terms of Use
    url: /meetup/terms/
    weight: 20
  - name: Privacy Policy
    url: /meetup/privacy/
    weight: 30
  - name: Support
    url: /meetup/support/
    weight: 40
